# Generated by Django 3.1.7 on 2021-04-10 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, verbose_name='Room Code')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='student_pic')),
                ('bday', models.DateField(null=True, verbose_name='Birth Day')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('zip_code', models.PositiveSmallIntegerField(null=True, verbose_name='Zip Code')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=55, null=True)),
                ('civil_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], max_length=55, null=True, verbose_name='Civil Status')),
                ('school_yr', models.CharField(default='2012', max_length=255)),
                ('sem', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], max_length=55)),
                ('slug', models.SlugField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.courses')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.school')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=556)),
                ('code', models.CharField(max_length=55, verbose_name='Subject Code')),
                ('unit', models.PositiveSmallIntegerField()),
                ('lab', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.courses')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='students.schedule')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='school.employees')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='SubjectAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.IntegerField()),
                ('status', models.CharField(choices=[('Passed', 'Passed'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('INC', 'INC')], max_length=255)),
                ('stud_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='average', to='students.studentsubject')),
            ],
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subjects'),
        ),
        migrations.AddField(
            model_name='students',
            name='subjects',
            field=models.ManyToManyField(through='students.StudentSubject', to='students.Subjects'),
        ),
        migrations.AddField(
            model_name='students',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
