# Generated by Django 3.1.7 on 2021-04-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='abs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
