# Generated by Django 3.1.7 on 2021-04-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210410_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='students.section'),
        ),
    ]
