# Generated by Django 3.1.7 on 2021-04-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentsubject_abs_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubject',
            name='avg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='status',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('INC', 'INC')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubjectAverage',
        ),
    ]
