# Generated by Django 3.1.7 on 2021-04-14 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20210414_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dead_line', models.DateTimeField(verbose_name='Dead Line')),
                ('description', models.TextField(max_length=5006)),
                ('assign', models.ManyToManyField(related_name='my_assignment', to='students.Students', verbose_name='Members')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dead_line', models.DateTimeField(verbose_name='Dead Line')),
                ('description', models.TextField(max_length=5006)),
                ('file', models.FileField(upload_to='project/')),
                ('assign', models.ManyToManyField(related_name='my_project', to='students.Students', verbose_name='Members')),
            ],
        ),
        migrations.CreateModel(
            name='FileAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignment/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_files', to='students.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_file', to='students.students')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='files',
            field=models.ManyToManyField(through='students.FileAssignment', to='students.Students'),
        ),
    ]
