# Generated by Django 3.1.7 on 2021-04-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20210414_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign',
            field=models.ManyToManyField(related_name='my_assignment', to='students.StudentSubject', verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='files',
            field=models.ManyToManyField(null=True, through='students.FileAssignment', to='students.Students'),
        ),
        migrations.AlterField(
            model_name='project',
            name='assign',
            field=models.ManyToManyField(related_name='my_project', to='students.StudentSubject', verbose_name='Members'),
        ),
    ]
