# Generated by Django 3.1.7 on 2021-04-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20210415_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign',
            field=models.ManyToManyField(null=True, related_name='my_assignment', to='students.StudentSubject', verbose_name='Members'),
        ),
    ]
