# Generated by Django 3.1.7 on 2021-04-15 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20210415_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign',
            field=models.ManyToManyField(blank=True, related_name='my_assignment', to='students.StudentSubject', verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='files',
            field=models.ManyToManyField(blank=True, through='students.FileAssignment', to='students.StudentSubject'),
        ),
        migrations.AlterField(
            model_name='fileassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_file', to='students.studentsubject'),
        ),
    ]
