# Generated by Django 3.1.7 on 2021-04-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20210416_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(null=True, upload_to='project/'),
        ),
    ]
