# Generated by Django 3.1.7 on 2021-04-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20210422_1130'),
        ('students', '0020_auto_20210420_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='school.employees'),
        ),
    ]
