# Generated by Django 3.1.7 on 2021-04-26 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_teachersubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubject',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.subjects'),
            preserve_default=False,
        ),
    ]
