# Generated by Django 3.1.7 on 2021-04-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_teachersubject_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='section',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subjects',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
