# Generated by Django 3.1.7 on 2021-04-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_auto_20210426_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='subjects',
            field=models.ManyToManyField(through='students.StudentSubject', to='students.TeacherSubject'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject', to='students.teachersubject'),
        ),
    ]
