# Generated by Django 3.1.7 on 2021-04-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_schedule_section_subjects_teachersubject'),
        ('students', '0025_auto_20210426_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='section',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='school.teachersubject'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='school.teachersubject'),
        ),
        migrations.AlterField(
            model_name='students',
            name='subjects',
            field=models.ManyToManyField(through='students.StudentSubject', to='school.TeacherSubject'),
        ),
        migrations.AlterField(
            model_name='studentsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject', to='school.teachersubject'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='TeacherSubject',
        ),
    ]
