# Generated by Django 3.1.7 on 2021-04-27 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20210427_0937'),
        ('students', '0026_auto_20210426_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='school.teachersubject'),
        ),
    ]
