# Generated by Django 3.2.1 on 2021-05-06 02:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('students', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPayedHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'School Holiday',
                'verbose_name_plural': 'School Holidays',
            },
        ),
        migrations.CreateModel(
            name='StudentBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bal', to='students.students')),
            ],
            options={
                'verbose_name': 'Student Balance',
                'verbose_name_plural': 'Student Balances',
            },
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='finance.studentbalance')),
            ],
            options={
                'verbose_name': 'Student Payment',
                'verbose_name_plural': 'Student Payments',
            },
        ),
        migrations.CreateModel(
            name='EmployeeOT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrs', models.PositiveIntegerField()),
                ('day', models.DateField()),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime', to='school.employees')),
            ],
            options={
                'verbose_name': 'Employee OT',
                'verbose_name_plural': 'Employee OTs',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='school.employees')),
            ],
            options={
                'verbose_name': 'Employee Leave',
                'verbose_name_plural': 'Employee Leaves',
            },
        ),
    ]
