# Generated by Django 3.1.7 on 2021-05-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='created',
            field=models.DateTimeField(default=False),
        ),
    ]
