# Generated by Django 3.1.7 on 2021-04-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210426_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeleave',
            options={'verbose_name': 'Employee Leave', 'verbose_name_plural': 'Employee Leaves'},
        ),
        migrations.AlterModelOptions(
            name='employeeot',
            options={'verbose_name': 'Employee OT', 'verbose_name_plural': 'Employee OTs'},
        ),
        migrations.AlterModelOptions(
            name='employeesalary',
            options={'verbose_name': 'Employee Salary', 'verbose_name_plural': 'Employee Salaries'},
        ),
        migrations.AlterModelOptions(
            name='schoolpayedholidays',
            options={'verbose_name': 'School Holiday', 'verbose_name_plural': 'School Holidays'},
        ),
        migrations.AlterModelOptions(
            name='studentbalance',
            options={'verbose_name': 'Student Balance', 'verbose_name_plural': 'Student Balances'},
        ),
        migrations.AlterModelOptions(
            name='studentpayment',
            options={'verbose_name': 'Student Payment', 'verbose_name_plural': 'Student Payments'},
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='week_hrs',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Weekly Hrs'),
            preserve_default=False,
        ),
    ]
