# Generated by Django 3.1.7 on 2021-05-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210502_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='created',
            field=models.DateTimeField(default=False, editable=False),
        ),
    ]
