# Generated by Django 3.1.7 on 2021-04-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210426_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='rate',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Daily Rate'),
            preserve_default=False,
        ),
    ]
