# Generated by Django 3.1.7 on 2021-04-29 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_employeesalary_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='finance.employeesalary'),
        ),
        migrations.AlterField(
            model_name='employeeot',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime', to='finance.employeesalary'),
        ),
    ]
