# Generated by Django 3.1.7 on 2021-05-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20210502_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='created',
            field=models.DateTimeField(blank=True, default=False, null=True),
        ),
    ]
