# Generated by Django 3.1.7 on 2021-05-02 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_studentpayment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
