# Generated by Django 3.1.7 on 2021-05-02 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_studentpayment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpayment',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='finance.studentbalance'),
        ),
    ]
