# Generated by Django 3.1.7 on 2021-04-10 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('vision', models.CharField(max_length=255, null=True)),
                ('mission', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('zip_code', models.PositiveSmallIntegerField(null=True, verbose_name='Zip Code')),
                ('date_funded', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=556)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='school.school')),
            ],
            options={
                'verbose_name': 'Policie',
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, null=True)),
                ('bday', models.DateField(null=True, verbose_name='Birth Day')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('zip_code', models.PositiveSmallIntegerField(null=True, verbose_name='Zip Code')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=55, null=True)),
                ('civil_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], max_length=55, null=True, verbose_name='Civil Status')),
                ('slug', models.SlugField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='school.department')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='school.school')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='school.school'),
        ),
        migrations.AddField(
            model_name='department',
            name='staff',
            field=models.ManyToManyField(through='school.Employees', to='school.School'),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BSBA', 'Bachelor of Science in Business'), ('BMS', 'Bachelor of Management Studies'), ('B.Acc', 'Bachelor of Accountancy'), ('BComp', 'Bachelor of Computing'), ('BCompSc', 'Bachelor of Computer Science'), ('BSc IT', 'Bachelor of Science in Information Technology')], max_length=556)),
                ('major', models.CharField(choices=[('MM', 'Marketing'), ('FM', 'Financial Management'), ('HRDM ', 'Human Resource Development')], max_length=556)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='school.school')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
