# Generated by Django 3.1.7 on 2021-04-20 02:24

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_school_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
