# Generated by Django 3.1.7 on 2021-04-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210420_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='country',
        ),
    ]
