# Generated by Django 3.1.7 on 2021-04-20 02:33

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_employees_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
