# Generated by Django 3.1.7 on 2021-04-20 02:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_employees_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='country',
            field=django_countries.fields.CountryField(default='PH', max_length=2),
        ),
    ]
