# Generated by Django 3.1.7 on 2021-04-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20210420_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='civil_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], default='Single', max_length=55, null=True, verbose_name='Civil Status'),
        ),
    ]
