# Generated by Django 3.1.7 on 2021-04-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20210420_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course',
            field=models.CharField(max_length=556),
        ),
        migrations.AlterField(
            model_name='courses',
            name='major',
            field=models.CharField(max_length=556),
        ),
    ]
