# Generated by Django 3.1.7 on 2021-04-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20210422_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course',
            field=models.CharField(max_length=556),
        ),
        migrations.AlterField(
            model_name='courses',
            name='major',
            field=models.CharField(max_length=556),
        ),
    ]
