# Generated by Django 3.1.7 on 2021-04-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20210422_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course',
            field=models.CharField(choices=[('BSBA', 'Bachelor of Science in Business'), ('BMS', 'Bachelor of Management Studies'), ('B.Acc', 'Bachelor of Accountancy'), ('BComp', 'Bachelor of Computing'), ('BCompSc', 'Bachelor of Computer Science'), ('BSc IT', 'Bachelor of Science in Information Technology'), ('Minor', 'Minor')], max_length=556),
        ),
        migrations.AlterField(
            model_name='courses',
            name='major',
            field=models.CharField(choices=[('MM', 'Marketing'), ('FM', 'Financial Management'), ('HRDM ', 'Human Resource Development'), ('Minor', 'Minor')], max_length=556),
        ),
    ]
