# Generated by Django 3.1.7 on 2021-04-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20210427_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubject',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
