# Generated by Django 3.1.7 on 2021-04-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20210428_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersubject',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='is_hr',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='employees',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employees',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
