# Generated by Django 3.1.7 on 2021-04-29 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20210428_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='staff',
        ),
    ]
