# Generated by Django 3.1.7 on 2021-04-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_subjects_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='rate',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Daily Rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='salary',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='week_hrs',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Weekly Hrs'),
            preserve_default=False,
        ),
    ]
