# Generated by Django 3.1.7 on 2021-04-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_auto_20210430_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='week_hrs',
            new_name='days_week',
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
